"""add Department

Revision ID: 91647b168c8e
Revises: e40265017da1
Create Date: 2026-02-18 14:26:27.931546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91647b168c8e'
down_revision = 'e40265017da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
